require ('./bx-capture');
require ('./bx-capture');
require ('./bx-dashboard');
require ('./bx-dialog');
require ('./bx-observation-inbox');
require ('./bx-observation-service');
require ('./bx-portfolio');
require ('./bx-resource-service');
require ('./bx-table');
require ('./bx-user-preferences');
require ('./bx-user-profile');
require ('./index');
require ('./md-sidenav-controller');
require('./bx-capture');
require('./bx-dashboard');
require('./bx-dialog');
require('./bx-observation-inbox');
require('./bx-observation-service');
require('./bx-portfolio');
require('./bx-resource-service');
require('./bx-table');
require('./bx-user-preferences');
require('./bx-user-profile');
require('./index');
require('./md-sidenav-controller');
